[package]
name = "fxa-client"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.6.0"
reqwest = "0.8.2"
hkdf = "*"
sha2 = "0.7.0"
hawk = "1.0.2"
error-chain = "0.11.0"
