[workspace]
members = [
    "components/fxa-client",
    "components/fxa-client/ffi",
    "components/logins",
    "components/logins/ffi",
    "components/places",
    "components/push",
    "components/push/ffi",
    "components/places/ffi",
    "components/support/cli",
    "components/support/sql",
    "components/support/ffi",
    "components/support/force-viaduct-reqwest",
    "components/support/interrupt",
    "components/support/rc_crypto",
    "components/support/rc_crypto/nss_sys",
    "components/viaduct",
    "components/sync15",
    "components/rc_log",
    "megazords/full",
    "megazords/fenix",
    "megazords/lockbox",
    "megazords/reference-browser",
    "megazords/ios/rust",
    "testing/sync-test",
]

[profile.release]
opt-level = "s"
debug = true
lto = true

[patch.crates-io]
# Until https://github.com/jgallagher/rusqlite/pull/511 lands and is in a release.
# Note: this uses a different branchname than that PR, to work around issues with
# various caches we have in CI (basically, the other branch got force pushed to,
# and our CI was never the same)
rusqlite = { git = "https://github.com/thomcc/rusqlite", branch = "sqlcipher-and-bundled" }
