[workspace]
members = [
    "fxa-client",
    "fxa-client/ffi",
    "sandvich/desktop",
    "sync15-adapter",
    "logins-sql",
    "logins-sql/ffi",
    "places"
]

[profile.release]
opt-level = "z"
debug = true
lto = true
