[package]
name = "nss_sys"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
edition = "2018"
license = "MPL-2.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
libloading = "0.5"
lazy_static = "1.3.0"
